device:
  layer: rpizero2w
  user1passhash: '$6$LC/akTfJOr451USD$IGaeArMZ7fKSDF44Z0qIAQj8Etd9QoaZyheb6MgcaFdXSjspirQp2nmctG2nlikMXgXYU/XzL9rflPOxFwQfp1'

layer:
  custom: rcm-injector

image:
  layer: image-rpios
  name: rpi-rcm-injector
  compression: xz
  root_part_size: 2000M
